// Constantes de dominio del CRM Skyward.
// Sin lógica, sin efectos secundarios.

export const STAGES = {
  RAPPORT:               { color:"#F39200", bg:"rgba(243,146,0,0.12)",  label:"Rapport" },
  CIERRE_SUAVE:          { color:"#FBBA00", bg:"rgba(251,186,0,0.12)",  label:"Cierre Suave" },
  LISTO_PARA_CIERRE:     { color:"#E84E0F", bg:"rgba(232,78,15,0.15)",  label:"🎯 Listo para cierre" },
  OFRECER_AGENDA:        { color:"#F39200", bg:"rgba(243,146,0,0.1)",   label:"Ofreciendo Reunión" },
  CONFIRMAR_AGENDA:      { color:"#10b981", bg:"rgba(16,185,129,0.1)",  label:"Confirmando" },
  RECOLECTAR_DATOS:      { color:"#FBBA00", bg:"rgba(251,186,0,0.1)",   label:"Recolectando datos" },
  SEGUIMIENTO_PENDIENTE: { color:"#646464", bg:"rgba(100,100,100,0.12)",label:"Agendado ✓" },
  HONORARIO_ENVIADO:     { color:"#F39200", bg:"rgba(243,146,0,0.12)",  label:"⚖️ Honorario enviado" },
  PENDIENTE_CONFIRMACION:{ color:"#E84E0F", bg:"rgba(232,78,15,0.1)",   label:"⏳ Espera confirm." },
};

export const FUNNEL_ORDER = [
  "RAPPORT",
  "CIERRE_SUAVE",
  "OFRECER_AGENDA",
  "CONFIRMAR_AGENDA",
  "SEGUIMIENTO_PENDIENTE",
];

export const PROF_COLORS = [
  '#E84E0F','#F39200','#FBBA00','#646464','#10b981',
  '#06b6d4','#f97316','#84cc16','#e11d48','#0ea5e9',
];

export const MONEDAS_MUNDO = [
  // Latinoamérica
  { code:"ARS", label:"Peso argentino" },
  { code:"CLP", label:"Peso chileno" },
  { code:"COP", label:"Peso colombiano" },
  { code:"MXN", label:"Peso mexicano" },
  { code:"PEN", label:"Sol peruano" },
  { code:"UYU", label:"Peso uruguayo" },
  { code:"PYG", label:"Guaraní paraguayo" },
  { code:"BOB", label:"Boliviano" },
  { code:"VES", label:"Bolívar venezolano" },
  { code:"BRL", label:"Real brasileño" },
  { code:"GTQ", label:"Quetzal guatemalteco" },
  { code:"HNL", label:"Lempira hondureño" },
  { code:"NIO", label:"Córdoba nicaragüense" },
  { code:"CRC", label:"Colón costarricense" },
  { code:"PAB", label:"Balboa panameño" },
  { code:"DOP", label:"Peso dominicano" },
  { code:"CUP", label:"Peso cubano" },
  { code:"HTG", label:"Gourde haitiano" },
  { code:"JMD", label:"Dólar jamaicano" },
  { code:"TTD", label:"Dólar de Trinidad" },
  { code:"BBD", label:"Dólar de Barbados" },
  { code:"BSD", label:"Dólar bahameño" },
  { code:"BZD", label:"Dólar de Belice" },
  { code:"GYD", label:"Dólar guyanés" },
  { code:"SRD", label:"Dólar surinamés" },
  // Norteamérica
  { code:"USD", label:"Dólar estadounidense" },
  { code:"CAD", label:"Dólar canadiense" },
  // Europa
  { code:"EUR", label:"Euro" },
  { code:"GBP", label:"Libra esterlina" },
  { code:"CHF", label:"Franco suizo" },
  { code:"NOK", label:"Corona noruega" },
  { code:"SEK", label:"Corona sueca" },
  { code:"DKK", label:"Corona danesa" },
  { code:"PLN", label:"Esloti polaco" },
  { code:"CZK", label:"Corona checa" },
  { code:"HUF", label:"Forinto húngaro" },
  { code:"RON", label:"Leu rumano" },
  { code:"HRK", label:"Kuna croata" },
  { code:"RSD", label:"Dinar serbio" },
  { code:"BGN", label:"Lev búlgaro" },
  { code:"UAH", label:"Grivna ucraniana" },
  { code:"RUB", label:"Rublo ruso" },
  { code:"TRY", label:"Lira turca" },
  // Asia / Pacífico
  { code:"JPY", label:"Yen japonés" },
  { code:"CNY", label:"Yuan chino" },
  { code:"INR", label:"Rupia india" },
  { code:"KRW", label:"Won surcoreano" },
  { code:"AUD", label:"Dólar australiano" },
  { code:"NZD", label:"Dólar neozelandés" },
  { code:"SGD", label:"Dólar de Singapur" },
  { code:"HKD", label:"Dólar de Hong Kong" },
  { code:"TWD", label:"Dólar taiwanés" },
  { code:"THB", label:"Baht tailandés" },
  { code:"MYR", label:"Ringgit malayo" },
  { code:"IDR", label:"Rupia indonesia" },
  { code:"PHP", label:"Peso filipino" },
  { code:"VND", label:"Dong vietnamita" },
  { code:"PKR", label:"Rupia pakistaní" },
  { code:"BDT", label:"Taka bangladesí" },
  { code:"LKR", label:"Rupia de Sri Lanka" },
  // Medio Oriente / África
  { code:"AED", label:"Dírham de EAU" },
  { code:"SAR", label:"Riyal saudí" },
  { code:"ILS", label:"Séquel israelí" },
  { code:"EGP", label:"Libra egipcia" },
  { code:"ZAR", label:"Rand sudafricano" },
  { code:"NGN", label:"Naira nigeriana" },
  { code:"KES", label:"Chelín keniano" },
  { code:"GHS", label:"Cedi ghanés" },
  { code:"MAD", label:"Dírham marroquí" },
  { code:"TND", label:"Dinar tunecino" },
];
